### ISSUE TITLE
Unzip the Archive.zip to make source code browsable

### ISSUE THREAD

**Issue by ekinoguz** [borismasis/send-to-calendar#2]
This will benefit people who are interested in the project, looking for an example Chrome extension, or even maybe willing to send a pull request to improve this extension.

**Comment by borismasis** [comment]
Thanks for the comment - archive.zip is just a zip file of the source which is already fully browsable in the same directory - it could be removed entirely from the repo

**Comment by ekinoguz** [comment]
Oh did not see `background.js` file, sorry.
