### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by clach04** [borismasis/send-to-calendar#6]
Hi!

Cool extension, please could you clarify the license?

http://borism.net/2012/12/26/open-sourced-send-to-calendar-chrome-extension/ indicates it is open source but doesnt specify the license type.

Thanks!

**Comment by borismasis** [comment]
Good point, just added GNU General Public License v3.0 

Cheers!

**Comment by clach04** [comment]
@borismasis Great! Thanks for doing that and for making this available.

I have a bunch of changes but I've not had/made time to make a pull request. I've also tested/got this working in Firefox. My fork/branch is at https://github.com/clach04/send-to-calendar/tree/mybranch in case you are interested.

**Comment by borismasis** [comment]
Great! That's pretty awesome. Will look for a pull request when you get a
chance and awesome to see this working in Firefox!
